version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      MODEL_FILE: model.joblib

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile-streamlit
    volumes:
      - .:/usr/src/app
    ports: 
      - "8501:8501"
    environment:
      STREAMLIT_SERVER_URL: http://api:8000